// Navigation tabs
export const navigationItems = [
  { id: "dashboard", label: "Dashboard" },
  { id: "issues", label: "Issues" },
  { id: "map", label: "Map" },
  {id:"departments",label:"Department"}
];

// Dummy issues (used when backend is unavailable)
// Dummy issues (used when backend is unavailable)
export const dummyIssues = [
  {
    id: 1,
    title: "Pothole near MG Road",
    description: "Large pothole causing traffic jams near MG Road, Bengaluru.",
    category: "Road Maintenance",
    status: "pending",
    priority: "high",
    department: "Public Works",
    place: "MG Road, Bengaluru",
    latitude: 12.9762,
    longitude: 77.6033,
    created_at: "2025-09-30T10:00:00Z",
  },
  {
    id: 2,
    title: "Streetlight not working",
    description: "Streetlight flickering near Lalbagh Botanical Garden.",
    category: "Electrical",
    status: "in_progress",
    priority: "medium",
    department: "Electricity Dept.",
    place: "Lalbagh Botanical Garden, Bengaluru",
    latitude: 12.9507,
    longitude: 77.5848,
    created_at: "2025-09-28T14:00:00Z",
  },
  {
    id: 3,
    title: "Overflowing garbage bins",
    description: "Bins not emptied near Brigade Road causing hygiene issues.",
    category: "Sanitation",
    status: "pending",
    priority: "high",
    department: "Sanitation",
    place: "Brigade Road, Bengaluru",
    latitude: 12.9716,
    longitude: 77.5946,
    created_at: "2025-09-27T09:30:00Z",
  },
  {
    id: 4,
    title: "Broken park bench",
    description: "Bench in Cubbon Park needs repair.",
    category: "Parks & Recreation",
    status: "pending",
    priority: "low",
    department: "Parks & Recreation",
    place: "Cubbon Park, Bengaluru",
    latitude: 12.9760,
    longitude: 77.5928,
    created_at: "2025-09-25T11:00:00Z",
  },
  {
    id: 5,
    title: "Traffic signal malfunction",
    description: "Signal at Koramangala junction not working properly.",
    category: "Traffic Management",
    status: "in_progress",
    priority: "high",
    department: "Traffic Management",
    place: "Koramangala, Bengaluru",
    latitude: 12.9352,
    longitude: 77.6245,
    created_at: "2025-09-24T08:45:00Z",
  },
  {
    id: 6,
    title: "Water leakage in main pipeline",
    description: "Water leakage causing disruption near Whitefield.",
    category: "Water Supply",
    status: "pending",
    priority: "high",
    department: "Water Supply",
    place: "Whitefield, Bengaluru",
    latitude: 12.9698,
    longitude: 77.7500,
    created_at: "2025-09-23T15:20:00Z",
  },
  {
    id: 7,
    title: "Fire hydrant blocked",
    description: "Fire hydrant near Marathahalli blocked by construction materials.",
    category: "Fire Department",
    status: "pending",
    priority: "medium",
    department: "Fire Department",
    place: "Marathahalli, Bengaluru",
    latitude: 12.9561,
    longitude: 77.7012,
    created_at: "2025-09-22T10:10:00Z",
  },
  {
    id: 8,
    title: "School building maintenance required",
    description: "Peeling walls and leaking roof in Govt. School.",
    category: "Education",
    status: "pending",
    priority: "medium",
    department: "Education Dept.",
    place: "Jayanagar, Bengaluru",
    latitude: 12.9250,
    longitude: 77.5938,
    created_at: "2025-09-21T13:15:00Z",
  },
  {
    id: 9,
    title: "Hospital waste disposal issue",
    description: "Medical waste not disposed properly near Fortis Hospital.",
    category: "Health Services",
    status: "in_progress",
    priority: "high",
    department: "Health Services",
    place: "Fortis Hospital, Bengaluru",
    latitude: 12.9350,
    longitude: 77.6240,
    created_at: "2025-09-20T09:00:00Z",
  },
  {
    id: 10,
    title: "Broken traffic signage",
    description: "Signage missing near Bannerghatta Road causing confusion.",
    category: "Traffic Management",
    status: "pending",
    priority: "low",
    department: "Traffic Management",
    place: "Bannerghatta Road, Bengaluru",
    latitude: 12.9255,
    longitude: 77.5838,
    created_at: "2025-09-19T12:30:00Z",
  },
];

// Dummy departments
export const dummyDepartments = [
  { id: 1, name: "Public Works", head: "Ramesh Kumar" },
  { id: 2, name: "Electricity Dept.", head: "Suresh Sharma" },
  { id: 3, name: "Water Supply", head: "Anil Mehta" },
  { id: 4, name: "Sanitation", head: "Priya Reddy" },
  { id: 5, name: "Road Maintenance", head: "Vikram Singh" },
  { id: 6, name: "Traffic Management", head: "Neha Gupta" },
  { id: 7, name: "Parks & Recreation", head: "Rohit Verma" },
  { id: 8, name: "Health Services", head: "Aarti Joshi" },
  { id: 9, name: "Fire Department", head: "Sanjay Patel" },
  { id: 10, name: "Education Dept.", head: "Ramesh Iyer" }
];
